[pytest]
testpaths = tests
asyncio_mode = auto
addopts =
    -v
    --tb=short
    --cov=.
    --cov-report=term-missing
    --cov-report=html
    --cov-report=xml
    --junitxml=junit.xml
filterwarnings =
    ignore::DeprecationWarning:pyModbusTCP.*
